"""AI-generated narrative summaries via Gemini (google-genai SDK).

Reads the model name from the GEMINI_MODEL environment variable
(preferring "gemini-3.1-pro-preview" when available). Since preview
models can be pulled or renamed without notice, this module tries a
configurable fallback chain rather than failing the whole report if the
preferred model is temporarily unavailable.

Only receives pre-computed, processed statistics (never raw OHLCV) —
Gemini interprets numbers the analytics layer already produced, so the
narrative is grounded in a fixed, auditable set of facts. This module
builds a full plain-text "facts sheet" out of every field already present
on `DailyStats` / `WeeklyStats` (session breakdown, key candle events,
drawdown/runup, weekly trend, etc.) so the model's closing write-up can be
genuinely comprehensive instead of a single generic sentence, while still
being unable to invent numbers that were never given to it.

Output contract for both `summarize_daily` and `summarize_weekly`: a
short multi-line Persian write-up, one short sentence per line, each line
opening with a single emoji (in the same house style already used
elsewhere in the report) — never a single flowing paragraph. The
deterministic disclaimer / channel-link footer is appended in code (never
generated by the model) so its wording and link are always exact.
"""

from __future__ import annotations

import time as time_module
from datetime import timedelta

from google import genai

from .exceptions import AIGenerationError
from .logger import get_logger
from .statistical_analyzer import DailyStats, SessionStat, WeeklyStats
from .time_manager import SERVER_TZ, TEHRAN_TZ

logger = get_logger(__name__)

# Short, same-model retries before falling through to the next model in the
# chain. Without this, a single transient network blip on the *preferred*
# model burns it for the whole run and silently downgrades every report to
# a fallback model — which defeats the purpose of preferring it in the
# first place. The google-genai SDK's exception hierarchy for transient vs.
# terminal (e.g. "model not found") errors isn't reliably distinguishable
# from here, so this stays a short, cheap retry rather than a long one.
SAME_MODEL_RETRY_ATTEMPTS = 2
SAME_MODEL_RETRY_DELAY_SECONDS = 2.0

# Appended deterministically in code (never generated by the model) so the
# disclaimer wording and channel link are always exact and cannot be
# altered or hallucinated by the LLM. Daily and weekly reports share the
# same disclaimer + channel line but differ in the middle "what this is"
# line, so the footer is built per report type rather than being one
# fixed constant.
TELEGRAM_CHANNEL_URL = "https://t.me/test5tts"
_DISCLAIMER_LINE = "📌 گزارش آماری داده واقعی؛ سیگنال یا پیش‌بینی نیست."
_CHANNEL_LINE = f"♾️ {TELEGRAM_CHANNEL_URL}"

FOOTER_TEXT_DAILY = (
    f"\n\n{_DISCLAIMER_LINE}"
    "\n📨 گزارش روزانه قبل از بازشدن نیویورک"
    f"\n{_CHANNEL_LINE}"
)
FOOTER_TEXT_WEEKLY = (
    f"\n\n{_DISCLAIMER_LINE}"
    "\n📨 گزارش هفتگی بازار"
    f"\n{_CHANNEL_LINE}"
)

_SESSION_FA_NAMES: dict[str, str] = {
    "Asia": "توکیو",
    "London": "لندن",
    "New York": "نیویورک",
}

_OUTPUT_FORMAT_SPEC = """Output format (follow exactly):
- Persian (Farsi) only, professional financial terminology, never transliterated.
- Plain text lines only — no headers, no markdown, no numbered/bulleted list syntax.
- Every line starts with exactly one emoji from this palette, chosen for what
  that line says (reuse an emoji if you need a second line of the same kind):
  📈 / 📉 overall tone or a directional fact, 🔥 the most active/eventful
  moment, 😴 the calmest/quietest stretch, ⚠️ a risk or level worth watching,
  🔺 / 🔻 the forward-looking outlook.
- Write 5 to 7 lines total. Do not write a single flowing paragraph and do
  not compress everything into 2-3 sentences — this must read as a genuinely
  comprehensive close-out, not a template filler.
- Cover, across those lines: (1) the overall character/tone of the period,
  (2) exactly which moment/session drove the most momentum, referencing the
  specific time or session given below, (3) the calmest/quietest stretch,
  (4) a concrete key level or risk to watch, (5) an explicit outlook —
  continuation vs. reversal — grounded only in the facts given.
- Never invent a number, time, or event that is not in the facts below.
- Do not include any disclaimer, sign-off, or channel link — those are
  appended separately in code."""

DAILY_PROMPT_TEMPLATE = """You are a professional market analyst writing the closing write-up of a
statistics-heavy daily report. All the numeric breakdown below has
ALREADY been shown to the reader in earlier sections of the report — do
not just repeat numbers verbatim, weave them into genuine analysis.

Asset: {asset_name}
Date (Asia/Tehran): {date_str}

Facts you may reference (do not invent anything beyond this):
{facts_block}

News context: {news_context}

{format_spec}
"""

WEEKLY_PROMPT_TEMPLATE = """You are a professional market analyst writing the closing write-up of a
statistics-heavy WEEKLY report. All the numeric breakdown below has
ALREADY been shown to the reader in earlier sections of the report — do
not just repeat numbers verbatim, weave them into genuine analysis. Use
weekly-specific framing (this is a week-over-week read, not a single
session) and weekly terminology: week open/close, weekly range,
volatility, average daily range, strongest/weakest trading day, trend —
not daily/session vocabulary like "امروز" or "امروز صبح".

Asset: {asset_name}
Week ending (Asia/Tehran): {date_str}

Facts you may reference (do not invent anything beyond this):
{facts_block}

Important USD news this week: {news_context}

{format_spec}
"""


def _dual_time(ts) -> str:
    """'سرور HH:MM (ایران HH:MM)' for a single UTC instant."""
    server_str = ts.astimezone(SERVER_TZ).strftime("%H:%M")
    tehran_str = ts.astimezone(TEHRAN_TZ).strftime("%H:%M")
    return f"سرور {server_str} (ایران {tehran_str})"


def _dual_hour_range(hour_start_utc) -> str:
    """Same as `_dual_time` but for a full clock-hour window."""
    hour_end_utc = hour_start_utc + timedelta(hours=1)
    server_start = hour_start_utc.astimezone(SERVER_TZ).strftime("%H:%M")
    server_end = hour_end_utc.astimezone(SERVER_TZ).strftime("%H:%M")
    tehran_start = hour_start_utc.astimezone(TEHRAN_TZ).strftime("%H:%M")
    tehran_end = hour_end_utc.astimezone(TEHRAN_TZ).strftime("%H:%M")
    return f"سرور {server_start}\u2013{server_end} (ایران {tehran_start}\u2013{tehran_end})"


def _session_facts_lines(session: SessionStat) -> list[str]:
    fa_name = _SESSION_FA_NAMES.get(session.name, session.name)
    lines = [f"- {fa_name} session:"]
    if session.high is None or session.low is None:
        lines.append("  no data")
        return lines

    lines.append(f"  range: {session.high - session.low:.2f}")
    if session.net_move is not None:
        lines.append(f"  net move: {session.net_move:+.2f}")
    if session.up_candles is not None and session.down_candles is not None:
        lines.append(
            f"  up/down candles: {session.up_candles}/{session.down_candles}"
            f" ({session.up_pct:.2f}% up)"
        )
    if session.biggest_up_candle is not None:
        lines.append(
            f"  biggest up 1m candle: {session.biggest_up_candle.value:+.2f}"
            f" at {_dual_time(session.biggest_up_candle.time_utc)}"
        )
    if session.biggest_down_candle is not None:
        lines.append(
            f"  biggest down 1m candle: {session.biggest_down_candle.value:.2f}"
            f" at {_dual_time(session.biggest_down_candle.time_utc)}"
        )
    if session.volume is not None:
        lines.append(f"  volume: {session.volume:,.0f}")
    if session.highest_5m_volume is not None:
        lines.append(
            f"  busiest 5m window: {_dual_time(session.highest_5m_volume.start_time_utc)}"
            f" -> {session.highest_5m_volume.volume:,.0f}"
        )
    return lines


def _daily_facts_block(stats: DailyStats) -> str:
    day_change = stats.close - stats.open
    direction = "bullish" if day_change >= 0 else "bearish"

    lines: list[str] = [
        f"- Open: {stats.open:.2f} / Close: {stats.close:.2f}"
        f" / Change: {day_change:+.2f} ({direction})",
    ]
    if stats.total_range is not None:
        lines.append(f"- Day range: {stats.total_range:.2f}")
    if stats.avg_candle_range is not None:
        lines.append(f"- Average 1m candle range: {stats.avg_candle_range:.2f}")
    if stats.up_candles is not None and stats.total_candles:
        lines.append(
            f"- Up/down candles: {stats.up_candles}/{stats.down_candles}"
            f" of {stats.total_candles} ({stats.up_pct:.2f}%/{stats.down_pct:.2f}%)"
        )
    lines.append(f"- Total volume: {stats.volume:,.0f}")
    if stats.highest_volume_session_name is not None:
        fa = _SESSION_FA_NAMES.get(
            stats.highest_volume_session_name, stats.highest_volume_session_name
        )
        lines.append(f"- Highest-volume session: {fa}")

    for session in stats.sessions:
        lines.extend(_session_facts_lines(session))

    if stats.overlap is not None:
        o = stats.overlap
        lines.append(
            f"- London-New York overlap: range {o.range:.2f}, "
            f"avg candle {o.avg_candle_range:.2f} "
            f"({o.pct_above_daily_avg:+.0f}% vs. daily average)"
        )

    if stats.busiest_hour is not None:
        lines.append(
            f"- Busiest (most volatile) hour: {_dual_hour_range(stats.busiest_hour.hour_start_utc)}"
            f" -> range {stats.busiest_hour.range:.2f}"
        )
    if stats.quietest_hour is not None:
        lines.append(
            f"- Quietest hour: {_dual_hour_range(stats.quietest_hour.hour_start_utc)}"
            f" -> range {stats.quietest_hour.range:.2f}"
        )
    if stats.biggest_range_candle is not None:
        lines.append(
            f"- Biggest single 1m candle range: {stats.biggest_range_candle.value:.2f}"
            f" at {_dual_time(stats.biggest_range_candle.time_utc)}"
        )
    if stats.second_biggest_range_candle is not None:
        lines.append(
            f"- Second biggest 1m candle range: {stats.second_biggest_range_candle.value:.2f}"
            f" at {_dual_time(stats.second_biggest_range_candle.time_utc)}"
        )
    if stats.highest_volume_1m is not None:
        lines.append(
            f"- Highest single-minute volume: {stats.highest_volume_1m.value:,.0f}"
            f" at {_dual_time(stats.highest_volume_1m.time_utc)}"
        )
    if stats.biggest_up_candle is not None:
        lines.append(
            f"- Biggest up 1m candle (whole day): {stats.biggest_up_candle.value:+.2f}"
            f" at {_dual_time(stats.biggest_up_candle.time_utc)}"
        )
    if stats.biggest_down_candle is not None:
        lines.append(
            f"- Biggest down 1m candle (whole day): {stats.biggest_down_candle.value:.2f}"
            f" at {_dual_time(stats.biggest_down_candle.time_utc)}"
        )
    if stats.max_drawdown is not None:
        dd = stats.max_drawdown
        lines.append(
            f"- Max drawdown: {dd.value:.2f} from {_dual_time(dd.start_time_utc)}"
            f" to {_dual_time(dd.end_time_utc)}"
        )
    if stats.max_runup is not None:
        ru = stats.max_runup
        lines.append(
            f"- Max runup: {ru.value:.2f} from {_dual_time(ru.start_time_utc)}"
            f" to {_dual_time(ru.end_time_utc)}"
        )

    return "\n".join(lines)


def _weekly_facts_block(stats: WeeklyStats) -> str:
    lines: list[str] = [
        f"- Week open: {stats.week_open:.2f} / Week close: {stats.week_close:.2f}"
        f" / Change: {stats.week_close - stats.week_open:+.2f}",
        f"- Week high: {stats.week_high:.2f} / Week low: {stats.week_low:.2f}",
        f"- Weekly range: {stats.weekly_range:.2f}",
        f"- Volatility (stddev of 1m log returns): {stats.volatility_pct:.4f}%",
        f"- Average daily range: {stats.average_daily_range:.2f}",
        f"- Strongest day: {stats.strongest_day.date}"
        f" (change {stats.strongest_day.close - stats.strongest_day.open:+.2f},"
        f" range {stats.strongest_day.range:.2f})",
        f"- Weakest day: {stats.weakest_day.date}"
        f" (change {stats.weakest_day.close - stats.weakest_day.open:+.2f},"
        f" range {stats.weakest_day.range:.2f})",
        f"- Highest-volume day: {stats.highest_volume_day.date}"
        f" (volume {stats.highest_volume_day.volume:,.0f})",
        f"- Most active hour (UTC): {stats.most_active_hour_utc}:00",
        f"- Trend: {stats.trend_summary}",
    ]

    if len(stats.daily_breakdown) > 1:
        lines.append("- Day-by-day breakdown:")
        for d in stats.daily_breakdown:
            lines.append(
                f"  {d.date}: open {d.open:.2f} -> close {d.close:.2f}"
                f" ({d.close - d.open:+.2f}), range {d.range:.2f}, volume {d.volume:,.0f}"
            )

    return "\n".join(lines)


class GeminiAnalyst:
    def __init__(self, api_key: str, model_chain: list[str]) -> None:
        self._client = genai.Client(api_key=api_key)
        self._model_chain = model_chain

    def _generate_with_model(self, model_name: str, prompt: str) -> str:
        """Tries a single model, with a couple of short retries for transient errors."""
        last_error: Exception | None = None
        for attempt in range(1, SAME_MODEL_RETRY_ATTEMPTS + 1):
            try:
                response = self._client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                )
                text = (response.text or "").strip()
                if text:
                    return text
                raise AIGenerationError(f"Empty response from model {model_name}")
            except Exception as exc:  # noqa: BLE001
                last_error = exc
                if attempt < SAME_MODEL_RETRY_ATTEMPTS:
                    logger.warning(
                        "Gemini model %s failed (attempt %d/%d): %s — retrying shortly.",
                        model_name, attempt, SAME_MODEL_RETRY_ATTEMPTS, exc,
                    )
                    time_module.sleep(SAME_MODEL_RETRY_DELAY_SECONDS)
        assert last_error is not None
        raise last_error

    def _generate(self, prompt: str) -> str:
        last_error: Exception | None = None
        for model_name in self._model_chain:
            try:
                logger.info("Requesting Gemini summary using model=%s", model_name)
                return self._generate_with_model(model_name, prompt)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Gemini model %s exhausted its retries: %s", model_name, exc)
                last_error = exc
                continue
        raise AIGenerationError(
            f"All Gemini models in the fallback chain failed. Last error: {last_error}"
        )

    def summarize_daily(
        self,
        asset_name: str,
        date_str: str,
        stats: DailyStats,
        news_context: str,
    ) -> str:
        prompt = DAILY_PROMPT_TEMPLATE.format(
            asset_name=asset_name,
            date_str=date_str,
            facts_block=_daily_facts_block(stats),
            news_context=news_context,
            format_spec=_OUTPUT_FORMAT_SPEC,
        )
        return self._generate(prompt) + FOOTER_TEXT_DAILY

    def summarize_weekly(
        self,
        asset_name: str,
        date_str: str,
        stats: WeeklyStats,
        news_context: str,
    ) -> str:
        prompt = WEEKLY_PROMPT_TEMPLATE.format(
            asset_name=asset_name,
            date_str=date_str,
            facts_block=_weekly_facts_block(stats),
            news_context=news_context,
            format_spec=_OUTPUT_FORMAT_SPEC,
        )
        return self._generate(prompt) + FOOTER_TEXT_WEEKLY


def get_gemini_analyst(api_key: str, model_chain: list[str]) -> GeminiAnalyst:
    return GeminiAnalyst(api_key=api_key, model_chain=model_chain)
