"""AI-generated narrative summaries via Gemini (google-genai SDK).

Reads the model name from the GEMINI_MODEL environment variable
(preferring "gemini-3.1-pro-preview" when available). Since preview
models can be pulled or renamed without notice, this module tries a
configurable fallback chain rather than failing the whole report if the
preferred model is temporarily unavailable.

Only receives pre-computed, processed statistics (never raw OHLCV) —
Gemini interprets numbers the analytics layer already produced, so the
narrative is grounded in a fixed, auditable set of facts.
"""

from __future__ import annotations

import time

from google import genai

from .exceptions import AIGenerationError
from .logger import get_logger
from .statistical_analyzer import DailyStats, WeeklyStats

logger = get_logger(__name__)

# Short, same-model retries before falling through to the next model in the
# chain. Without this, a single transient network blip on the *preferred*
# model burns it for the whole run and silently downgrades every report to
# a fallback model — which defeats the purpose of preferring it in the
# first place. The google-genai SDK's exception hierarchy for transient vs.
# terminal (e.g. "model not found") errors isn't reliably distinguishable
# from here, so this stays a short, cheap retry rather than a long one.
SAME_MODEL_RETRY_ATTEMPTS = 2
SAME_MODEL_RETRY_DELAY_SECONDS = 2.0

# Appended deterministically in code (never generated by the model) so the
# disclaimer wording and channel link are always exact and cannot be
# altered or hallucinated by the LLM.
TELEGRAM_CHANNEL_URL = "https://t.me/test5tts"
FOOTER_TEXT = (
    "\n\nاین تحلیل سیگنال معامله نیست و صرفاً بررسی علمی و آماری است."
    f"\nتحلیل و آنالیز هرروزه‌ی دیتا در کانال تلگرام: {TELEGRAM_CHANNEL_URL}"
)

DAILY_PROMPT_TEMPLATE = """You are a professional market analyst writing the closing wrap-up
paragraph of a statistics-heavy daily report. All the numeric breakdown
(OHLCV, per-session stats, key candle events, drawdown/runup) has ALREADY
been shown to the reader above this paragraph in a separate section — do
not repeat those numbers verbatim, just refer to them narratively.

Asset: {asset_name}
Date (Asia/Tehran): {date_str}

Facts you may reference (do not invent anything beyond this):
- Day direction: {direction} ({day_change:+.2f})
- Busiest hour (most volatile, UTC {busiest_hour_utc}:00): range {busiest_hour_range:.2f}
- Quietest hour (UTC {quietest_hour_utc}:00): range {quietest_hour_range:.2f}
- Highest-volume session: {highest_volume_session}
- Session net moves: {session_lines}

News context: {news_context}

Write exactly two parts, in Persian (Farsi), plain prose, no headers, no
markdown, no bullet points:
1. A 2-3 sentence recap: which hour/session released the most momentum,
   how the rest of the day compared, and the overall tone.
2. A 1-2 sentence near-term outlook for the upcoming session based only on
   the facts above (trend continuation vs. reversal risk, a key level to
   watch) — do not invent data not given above.
Use professional financial Persian terminology (do not transliterate — use
proper Farsi words). Do not include any disclaimer or sign-off — that will
be added separately.
"""

WEEKLY_PROMPT_TEMPLATE = """You are a professional market analyst writing a concise weekly report.

Asset: {asset_name}
Week ending (Asia/Tehran): {date_str}

Weekly statistics:
- Open: {week_open:.2f}
- High: {week_high:.2f}
- Low: {week_low:.2f}
- Close: {week_close:.2f}
- Weekly range: {weekly_range:.2f}
- Volatility (stddev of 1m log returns): {volatility_pct:.4f}%
- Average daily range: {average_daily_range:.2f}
- Strongest day: {strongest_day_date} (close-open change)
- Weakest day: {weakest_day_date} (close-open change)
- Highest volume day: {highest_volume_day_date}
- Most active hour (UTC): {most_active_hour_utc}:00
- Trend: {trend_summary}

Important USD news this week: {news_context}

Write a 5-6 sentence professional weekly briefing in Persian (Farsi) summarizing
the price action, volatility, and the trend. Then add 1-2 sentences with a
short outlook for next week based only on the data above (trend continuation
vs. reversal risk, key level to watch) — do not invent data that is not
given above. No headers, plain prose only. Use professional financial
Persian terminology (do not transliterate — use proper Farsi words). Do not
include any disclaimer or sign-off — that will be added separately.
"""


class GeminiAnalyst:
    def __init__(self, api_key: str, model_chain: list[str]) -> None:
        self._client = genai.Client(api_key=api_key)
        self._model_chain = model_chain

    def _generate_with_model(self, model_name: str, prompt: str) -> str:
        """Tries a single model, with a couple of short retries for transient errors."""
        last_error: Exception | None = None
        for attempt in range(1, SAME_MODEL_RETRY_ATTEMPTS + 1):
            try:
                response = self._client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                )
                text = (response.text or "").strip()
                if text:
                    return text
                raise AIGenerationError(f"Empty response from model {model_name}")
            except Exception as exc:  # noqa: BLE001
                last_error = exc
                if attempt < SAME_MODEL_RETRY_ATTEMPTS:
                    logger.warning(
                        "Gemini model %s failed (attempt %d/%d): %s — retrying shortly.",
                        model_name, attempt, SAME_MODEL_RETRY_ATTEMPTS, exc,
                    )
                    time.sleep(SAME_MODEL_RETRY_DELAY_SECONDS)
        assert last_error is not None
        raise last_error

    def _generate(self, prompt: str) -> str:
        last_error: Exception | None = None
        for model_name in self._model_chain:
            try:
                logger.info("Requesting Gemini summary using model=%s", model_name)
                return self._generate_with_model(model_name, prompt)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Gemini model %s exhausted its retries: %s", model_name, exc)
                last_error = exc
                continue
        raise AIGenerationError(
            f"All Gemini models in the fallback chain failed. Last error: {last_error}"
        )

    def summarize_daily(
        self,
        asset_name: str,
        date_str: str,
        stats: DailyStats,
        news_context: str,
    ) -> str:
        session_lines = "; ".join(
            f"{s.name}: {s.net_move:+.2f}" for s in stats.sessions if s.net_move is not None
        ) or "no session data"
        day_change = stats.close - stats.open
        direction = "bullish" if day_change >= 0 else "bearish"

        prompt = DAILY_PROMPT_TEMPLATE.format(
            asset_name=asset_name,
            date_str=date_str,
            direction=direction,
            day_change=day_change,
            busiest_hour_utc=(
                stats.busiest_hour.hour_start_utc.hour if stats.busiest_hour else 0
            ),
            busiest_hour_range=(stats.busiest_hour.range if stats.busiest_hour else 0.0),
            quietest_hour_utc=(
                stats.quietest_hour.hour_start_utc.hour if stats.quietest_hour else 0
            ),
            quietest_hour_range=(stats.quietest_hour.range if stats.quietest_hour else 0.0),
            highest_volume_session=(stats.highest_volume_session_name or "unknown"),
            session_lines=session_lines,
            news_context=news_context,
        )
        return self._generate(prompt) + FOOTER_TEXT

    def summarize_weekly(
        self,
        asset_name: str,
        date_str: str,
        stats: WeeklyStats,
        news_context: str,
    ) -> str:
        prompt = WEEKLY_PROMPT_TEMPLATE.format(
            asset_name=asset_name,
            date_str=date_str,
            week_open=stats.week_open,
            week_high=stats.week_high,
            week_low=stats.week_low,
            week_close=stats.week_close,
            weekly_range=stats.weekly_range,
            volatility_pct=stats.volatility_pct,
            average_daily_range=stats.average_daily_range,
            strongest_day_date=stats.strongest_day.date,
            weakest_day_date=stats.weakest_day.date,
            highest_volume_day_date=stats.highest_volume_day.date,
            most_active_hour_utc=stats.most_active_hour_utc,
            trend_summary=stats.trend_summary,
            news_context=news_context,
        )
        return self._generate(prompt) + FOOTER_TEXT


def get_gemini_analyst(api_key: str, model_chain: list[str]) -> GeminiAnalyst:
    return GeminiAnalyst(api_key=api_key, model_chain=model_chain)
