"""AI-generated narrative analysis via Gemini (google-genai SDK).

Reads the model name from the GEMINI_MODEL environment variable
(preferring "gemini-3.1-pro-preview" when available). Since preview
models can be pulled or renamed without notice, this module tries a
configurable fallback chain rather than failing the whole report if the
preferred model is temporarily unavailable.

Only receives pre-computed, processed statistics (never raw OHLCV) —
Gemini interprets numbers the analytics layer already produced, so the
narrative is grounded in a fixed, auditable set of facts. This module
builds a full plain-text "facts sheet" out of every field already present
on `DailyStats` / `WeeklyStats` (session breakdown, key candle events,
drawdown/runup, weekly trend, day/week high-low, etc.) so the model's
write-up can be genuinely comprehensive instead of a single generic
sentence, while still being unable to invent numbers it was never given.

Each `summarize_*` call returns TWO blocks in one response:
  1. A short statistical recap ("تحلیل آماری") — backward-looking, what
     actually happened.
  2. A short scenario outlook ("چشم‌انداز احتمالی") — three forward-looking
     price scenarios (bullish continuation / corrective pullback /
     trend-weakening breakdown), each anchored to a real level already in
     the facts (close, day/week high, day/week low, open) so the model
     can't invent a price out of thin air.
The two blocks are joined with `SECTION_SPLIT_MARKER` so
`message_formatter.py` can place them in separate numbered report
sections without a second model call. The deterministic disclaimer +
channel-link footer is appended to the outlook block in code (never
generated by the model) so its wording and link are always exact.
"""

from __future__ import annotations

import time as time_module
from datetime import timedelta

from google import genai

from .exceptions import AIGenerationError
from .logger import get_logger
from .statistical_analyzer import DailyStats, SessionStat, WeeklyStats
from .time_manager import SERVER_TZ, TEHRAN_TZ

logger = get_logger(__name__)

# Short, same-model retries before falling through to the next model in the
# chain. Without this, a single transient network blip on the *preferred*
# model burns it for the whole run and silently downgrades every report to
# a fallback model — which defeats the purpose of preferring it in the
# first place. The google-genai SDK's exception hierarchy for transient vs.
# terminal (e.g. "model not found") errors isn't reliably distinguishable
# from here, so this stays a short, cheap retry rather than a long one.
SAME_MODEL_RETRY_ATTEMPTS = 2
SAME_MODEL_RETRY_DELAY_SECONDS = 2.0

# Internal marker joining the two blocks returned by `summarize_daily` /
# `summarize_weekly`; `message_formatter.py` splits on this to place each
# block in its own numbered section. Never shown to the reader.
SECTION_SPLIT_MARKER = "\n\u2063SECTION_SPLIT\u2063\n"

# Marker the MODEL is asked to emit between the two blocks in its raw
# response, so a single generation call can be parsed into both pieces.
# Deliberately distinct from SECTION_SPLIT_MARKER above (that one is our
# internal, code-only join — this one only ever exists transiently in the
# model's raw text and is stripped out before SECTION_SPLIT_MARKER is used).
_MODEL_OUTLOOK_MARKER = "===OUTLOOK==="

# Appended deterministically in code (never generated by the model) so the
# disclaimer wording and channel link are always exact and cannot be
# altered or hallucinated by the LLM.
TELEGRAM_CHANNEL_URL = "https://t.me/GDBPULSE"
_DISCLAIMER_LINE = (
    "📌 سناریوها صرفاً بر اساس رفتار آماری و ساختار قیمت هستند و سیگنال معاملاتی نیستند."
)
_CHANNEL_LINE = f"♾️ {TELEGRAM_CHANNEL_URL}"

FOOTER_TEXT_DAILY = (
    f"\n{_DISCLAIMER_LINE}"
    "\n📨 گزارش روزانه بازار | هر روز، ۳۰ دقیقه قبل از بازگشایی نیویورک"
    f"\n\n{_CHANNEL_LINE}"
)
FOOTER_TEXT_WEEKLY = (
    f"\n{_DISCLAIMER_LINE}"
    "\n📨 گزارش هفتگی بازار"
    f"\n\n{_CHANNEL_LINE}"
)

_SESSION_FA_NAMES: dict[str, str] = {
    "Asia": "توکیو",
    "London": "لندن",
    "New York": "نیویورک",
}

_OUTPUT_FORMAT_SPEC = f"""Output format (follow exactly):
- Persian (Farsi) only, professional financial terminology, never transliterated.
- Plain text lines only — no headers, no markdown, no numbered/bulleted list syntax.
- Never invent a number, time, price level, or event that is not in the
  facts below or directly derivable from them (e.g. "just above the day's
  high" when the day's high is given).

Write TWO blocks, in this exact order, separated by a line that contains
ONLY the literal text {_MODEL_OUTLOOK_MARKER} (nothing else on that line):

BLOCK 1 — statistical recap, exactly 3 lines:
- Line 1 starts with 📈 or 📉: the main driver of the overall move (which
  waves/moments actually produced the change — not just candle counts).
- Line 2 starts with 🔥: exactly where liquidity/momentum concentrated
  (name the session, overlap, or specific time from the facts).
- Line 3 starts with 🔺 or 🔻: a closing/positioning observation — e.g. how
  the close sits relative to the day's/week's range, or the effect of the
  drawdown/runup on the final position.

BLOCK 2 — scenario outlook, exactly 3 lines, each anchored to a real level
from the facts (close, open, day/week high, day/week low — or a level
clearly derived from them, like "a break above the high"):
- Line 1 starts with 🟢 سناریوی صعودی:  — the bullish-continuation
  condition and the level/zone that would confirm it.
- Line 2 starts with 🟡 سناریوی اصلاحی:  — the corrective/pullback
  condition and the support zone price is likely to test.
- Line 3 starts with 🔴 سناریوی ضعیف‌شدن روند:  — the condition that would
  weaken the day's/week's structure and the level whose breakdown would
  confirm it.
Do not include any disclaimer, sign-off, or channel link in either block —
those are appended separately in code."""

DAILY_PROMPT_TEMPLATE = """You are a professional market analyst writing the closing analysis of a
statistics-heavy daily report. All the numeric breakdown below has
ALREADY been shown to the reader in earlier sections of the report — do
not just repeat numbers verbatim, weave them into genuine analysis.

Asset: {asset_name}
Date (Asia/Tehran): {date_str}

Facts you may reference (do not invent anything beyond this):
{facts_block}

News context: {news_context}

{format_spec}
"""

WEEKLY_PROMPT_TEMPLATE = """You are a professional market analyst writing the closing analysis of a
statistics-heavy WEEKLY report. All the numeric breakdown below has
ALREADY been shown to the reader in earlier sections of the report — do
not just repeat numbers verbatim, weave them into genuine analysis. Use
weekly-specific framing (this is a week-over-week read, not a single
session) and weekly terminology: week open/close, weekly range,
volatility, average daily range, strongest/weakest trading day, trend —
not daily/session vocabulary like "امروز" or "امروز صبح".

Asset: {asset_name}
Week ending (Asia/Tehran): {date_str}

Facts you may reference (do not invent anything beyond this):
{facts_block}

Important USD news this week: {news_context}

{format_spec}
"""


def _dual_time(ts) -> str:
    """'سرور HH:MM (ایران HH:MM)' for a single UTC instant."""
    server_str = ts.astimezone(SERVER_TZ).strftime("%H:%M")
    tehran_str = ts.astimezone(TEHRAN_TZ).strftime("%H:%M")
    return f"سرور {server_str} (ایران {tehran_str})"


def _dual_hour_range(hour_start_utc) -> str:
    """Same as `_dual_time` but for a full clock-hour window."""
    hour_end_utc = hour_start_utc + timedelta(hours=1)
    server_start = hour_start_utc.astimezone(SERVER_TZ).strftime("%H:%M")
    server_end = hour_end_utc.astimezone(SERVER_TZ).strftime("%H:%M")
    tehran_start = hour_start_utc.astimezone(TEHRAN_TZ).strftime("%H:%M")
    tehran_end = hour_end_utc.astimezone(TEHRAN_TZ).strftime("%H:%M")
    return f"سرور {server_start}\u2013{server_end} (ایران {tehran_start}\u2013{tehran_end})"


def _session_facts_lines(session: SessionStat) -> list[str]:
    fa_name = _SESSION_FA_NAMES.get(session.name, session.name)
    lines = [f"- {fa_name} session:"]
    if session.high is None or session.low is None:
        lines.append("  no data")
        return lines

    lines.append(f"  range: {session.high - session.low:.2f}")
    if session.net_move is not None:
        lines.append(f"  net move: {session.net_move:+.2f}")
    if session.up_candles is not None and session.down_candles is not None:
        lines.append(
            f"  up/down candles: {session.up_candles}/{session.down_candles}"
            f" ({session.up_pct:.2f}% up)"
        )
    if session.biggest_up_candle is not None:
        lines.append(
            f"  biggest up 1m candle: {session.biggest_up_candle.value:+.2f}"
            f" at {_dual_time(session.biggest_up_candle.time_utc)}"
        )
    if session.biggest_down_candle is not None:
        lines.append(
            f"  biggest down 1m candle: {session.biggest_down_candle.value:.2f}"
            f" at {_dual_time(session.biggest_down_candle.time_utc)}"
        )
    if session.volume is not None:
        lines.append(f"  volume: {session.volume:,.0f}")
    if session.highest_5m_volume is not None:
        lines.append(
            f"  busiest 5m window: {_dual_time(session.highest_5m_volume.start_time_utc)}"
            f" -> {session.highest_5m_volume.volume:,.0f}"
        )
    return lines


def _daily_facts_block(stats: DailyStats) -> str:
    day_change = stats.close - stats.open
    direction = "bullish" if day_change >= 0 else "bearish"

    lines: list[str] = [
        f"- Open: {stats.open:.2f} / Close: {stats.close:.2f}"
        f" / Change: {day_change:+.2f} ({direction})",
        f"- Day high: {stats.high:.2f} / Day low: {stats.low:.2f}",
    ]
    if stats.total_range is not None:
        lines.append(f"- Day range: {stats.total_range:.2f}")
    if stats.avg_candle_range is not None:
        lines.append(f"- Average 1m candle range: {stats.avg_candle_range:.2f}")
    if stats.up_candles is not None and stats.total_candles:
        neutral_candles = stats.total_candles - stats.up_candles - stats.down_candles
        lines.append(
            f"- Up/down/neutral candles: {stats.up_candles}/{stats.down_candles}"
            f"/{neutral_candles} of {stats.total_candles}"
        )
    lines.append(f"- Total volume: {stats.volume:,.0f}")
    if stats.highest_volume_session_name is not None:
        fa = _SESSION_FA_NAMES.get(
            stats.highest_volume_session_name, stats.highest_volume_session_name
        )
        lines.append(f"- Highest-volume session: {fa}")

    for session in stats.sessions:
        lines.extend(_session_facts_lines(session))

    if stats.overlap is not None:
        o = stats.overlap
        lines.append(
            f"- London-New York overlap: range {o.range:.2f}, "
            f"avg candle {o.avg_candle_range:.2f} "
            f"({o.pct_above_daily_avg:+.0f}% vs. daily average)"
        )

    if stats.busiest_hour is not None:
        lines.append(
            f"- Busiest (most volatile) hour: {_dual_hour_range(stats.busiest_hour.hour_start_utc)}"
            f" -> range {stats.busiest_hour.range:.2f}"
        )
    if stats.quietest_hour is not None:
        lines.append(
            f"- Quietest hour: {_dual_hour_range(stats.quietest_hour.hour_start_utc)}"
            f" -> range {stats.quietest_hour.range:.2f}"
        )
    if stats.biggest_range_candle is not None:
        lines.append(
            f"- Biggest single 1m candle range: {stats.biggest_range_candle.value:.2f}"
            f" at {_dual_time(stats.biggest_range_candle.time_utc)}"
        )
    if stats.highest_volume_1m is not None:
        lines.append(
            f"- Highest single-minute volume: {stats.highest_volume_1m.value:,.0f}"
            f" at {_dual_time(stats.highest_volume_1m.time_utc)}"
        )
    if stats.biggest_up_candle is not None:
        lines.append(
            f"- Biggest up 1m candle (whole day): {stats.biggest_up_candle.value:+.2f}"
            f" at {_dual_time(stats.biggest_up_candle.time_utc)}"
        )
    if stats.biggest_down_candle is not None:
        lines.append(
            f"- Biggest down 1m candle (whole day): {stats.biggest_down_candle.value:.2f}"
            f" at {_dual_time(stats.biggest_down_candle.time_utc)}"
        )
    if stats.max_drawdown is not None:
        dd = stats.max_drawdown
        lines.append(
            f"- Max drawdown: {dd.value:.2f} from {_dual_time(dd.start_time_utc)}"
            f" to {_dual_time(dd.end_time_utc)}"
        )
    if stats.max_runup is not None:
        ru = stats.max_runup
        lines.append(
            f"- Max runup: {ru.value:.2f} from {_dual_time(ru.start_time_utc)}"
            f" to {_dual_time(ru.end_time_utc)}"
        )

    return "\n".join(lines)


def _weekly_facts_block(stats: WeeklyStats) -> str:
    lines: list[str] = [
        f"- Week open: {stats.week_open:.2f} / Week close: {stats.week_close:.2f}"
        f" / Change: {stats.week_close - stats.week_open:+.2f}",
        f"- Week high: {stats.week_high:.2f} / Week low: {stats.week_low:.2f}",
        f"- Weekly range: {stats.weekly_range:.2f}",
        f"- Volatility (stddev of 1m log returns): {stats.volatility_pct:.4f}%",
        f"- Average daily range: {stats.average_daily_range:.2f}",
        f"- Strongest day: {stats.strongest_day.date}"
        f" (change {stats.strongest_day.close - stats.strongest_day.open:+.2f},"
        f" range {stats.strongest_day.range:.2f})",
        f"- Weakest day: {stats.weakest_day.date}"
        f" (change {stats.weakest_day.close - stats.weakest_day.open:+.2f},"
        f" range {stats.weakest_day.range:.2f})",
        f"- Highest-volume day: {stats.highest_volume_day.date}"
        f" (volume {stats.highest_volume_day.volume:,.0f})",
        f"- Most active hour (UTC): {stats.most_active_hour_utc}:00",
        f"- Trend: {stats.trend_summary}",
    ]

    if len(stats.daily_breakdown) > 1:
        lines.append("- Day-by-day breakdown:")
        for d in stats.daily_breakdown:
            lines.append(
                f"  {d.date}: open {d.open:.2f} -> close {d.close:.2f}"
                f" ({d.close - d.open:+.2f}), range {d.range:.2f}, volume {d.volume:,.0f}"
            )

    return "\n".join(lines)


def _split_analysis_and_outlook(raw_text: str) -> tuple[str, str]:
    """Splits the model's raw response on `_MODEL_OUTLOOK_MARKER` into
    (analysis_block, outlook_block). If the model didn't include the
    marker (should be rare given the format spec, but LLM output is never
    100% guaranteed), the whole response is treated as the analysis block
    and the outlook block is left empty rather than raising — a degraded
    report (missing section 4's AI content) is better than no report."""
    if _MODEL_OUTLOOK_MARKER in raw_text:
        analysis, outlook = raw_text.split(_MODEL_OUTLOOK_MARKER, 1)
        return analysis.strip(), outlook.strip()
    logger.warning(
        "Gemini response did not contain the expected '%s' marker; "
        "outlook block will be empty.", _MODEL_OUTLOOK_MARKER,
    )
    return raw_text.strip(), ""


class GeminiAnalyst:
    def __init__(self, api_key: str, model_chain: list[str]) -> None:
        self._client = genai.Client(api_key=api_key)
        self._model_chain = model_chain

    def _generate_with_model(self, model_name: str, prompt: str) -> str:
        """Tries a single model, with a couple of short retries for transient errors."""
        last_error: Exception | None = None
        for attempt in range(1, SAME_MODEL_RETRY_ATTEMPTS + 1):
            try:
                response = self._client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                )
                text = (response.text or "").strip()
                if text:
                    return text
                raise AIGenerationError(f"Empty response from model {model_name}")
            except Exception as exc:  # noqa: BLE001
                last_error = exc
                if attempt < SAME_MODEL_RETRY_ATTEMPTS:
                    logger.warning(
                        "Gemini model %s failed (attempt %d/%d): %s — retrying shortly.",
                        model_name, attempt, SAME_MODEL_RETRY_ATTEMPTS, exc,
                    )
                    time_module.sleep(SAME_MODEL_RETRY_DELAY_SECONDS)
        assert last_error is not None
        raise last_error

    def _generate(self, prompt: str) -> str:
        last_error: Exception | None = None
        for model_name in self._model_chain:
            try:
                logger.info("Requesting Gemini summary using model=%s", model_name)
                return self._generate_with_model(model_name, prompt)
            except Exception as exc:  # noqa: BLE001
                logger.warning("Gemini model %s exhausted its retries: %s", model_name, exc)
                last_error = exc
                continue
        raise AIGenerationError(
            f"All Gemini models in the fallback chain failed. Last error: {last_error}"
        )

    def summarize_daily(
        self,
        asset_name: str,
        date_str: str,
        stats: DailyStats,
        news_context: str,
    ) -> str:
        prompt = DAILY_PROMPT_TEMPLATE.format(
            asset_name=asset_name,
            date_str=date_str,
            facts_block=_daily_facts_block(stats),
            news_context=news_context,
            format_spec=_OUTPUT_FORMAT_SPEC,
        )
        raw = self._generate(prompt)
        analysis, outlook = _split_analysis_and_outlook(raw)
        return analysis + SECTION_SPLIT_MARKER + outlook + FOOTER_TEXT_DAILY

    def summarize_weekly(
        self,
        asset_name: str,
        date_str: str,
        stats: WeeklyStats,
        news_context: str,
    ) -> str:
        prompt = WEEKLY_PROMPT_TEMPLATE.format(
            asset_name=asset_name,
            date_str=date_str,
            facts_block=_weekly_facts_block(stats),
            news_context=news_context,
            format_spec=_OUTPUT_FORMAT_SPEC,
        )
        raw = self._generate(prompt)
        analysis, outlook = _split_analysis_and_outlook(raw)
        return analysis + SECTION_SPLIT_MARKER + outlook + FOOTER_TEXT_WEEKLY


def get_gemini_analyst(api_key: str, model_chain: list[str]) -> GeminiAnalyst:
    return GeminiAnalyst(api_key=api_key, model_chain=model_chain)
